# - Find PHP5
# This module finds if PHP5 is installed and determines where the include files
# and libraries are. It also determines what the name of the library is. This
# code sets the following variables:
#
#  PHP5_INCLUDE_PATH       = path to where php.h can be found
#  PHP5_EXECUTABLE         = full path to the php4 binary
#
#  file is derived from FindPHP4.cmake
#

cmake_minimum_required(VERSION 2.8)

SET(PHP5_FOUND "NO")

FIND_PROGRAM(PHP5_EXECUTABLE NAMES php PATHS /usr/local/php5/bin)

MARK_AS_ADVANCED(
  PHP5_EXECUTABLE
  PHP5_FOUND_INCLUDE_PATH
)

FIND_PROGRAM(PHP5_CONFIG_EXECUTABLE NAMES php-config PATHS /usr/local/php5/bin)

EXECUTE_PROCESS(COMMAND ${PHP5_CONFIG_EXECUTABLE} --version
   OUTPUT_VARIABLE PHP5_VERSION)
STRING(REPLACE "\n" "" PHP5_VERSION "${PHP5_VERSION}")

EXECUTE_PROCESS(COMMAND ${PHP5_CONFIG_EXECUTABLE} --extension-dir
   OUTPUT_VARIABLE PHP5_EXTENSION_DIR)
STRING(REPLACE "\n" "" PHP5_EXTENSION_DIR "${PHP5_EXTENSION_DIR}")

EXECUTE_PROCESS(COMMAND ${PHP5_CONFIG_EXECUTABLE} --includes
   OUTPUT_VARIABLE PHP5_INCLUDES)
STRING(REPLACE "\n" "" PHP5_INCLUDES "${PHP5_INCLUDES}")
STRING(REPLACE "-I" ";" PHP5_INCLUDES "${PHP5_INCLUDES}")
STRING(REPLACE " " "" PHP5_INCLUDES "${PHP5_INCLUDES}")

EXECUTE_PROCESS(COMMAND ${PHP5_CONFIG_EXECUTABLE} --include-dir
   OUTPUT_VARIABLE PHP5_INCLUDE_DIR)
STRING(REPLACE "\n" "" PHP5_INCLUDE_DIR "${PHP5_INCLUDE_DIR}")

EXECUTE_PROCESS(COMMAND ${PHP5_CONFIG_EXECUTABLE} --prefix
   OUTPUT_VARIABLE PHP5_PREFIX)
STRING(REPLACE "\n" "" PHP5_PREFIX "${PHP5_PREFIX}")

SET(PHP5_MAIN_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/main)
SET(PHP5_TSRM_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/TSRM)
SET(PHP5_ZEND_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/Zend)
SET(PHP5_REGEX_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/regex)
SET(PHP5_EXT_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/ext)
SET(PHP5_DATE_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/ext/date/lib)
SET(PHP5_STANDARD_INCLUDE_DIR ${PHP5_INCLUDE_DIR}/ext/standard)

IF(PHP5_VERSION LESS 5)
    MESSAGE(FATAL_ERROR "PHP version is not 5 or later")
ENDIF(PHP5_VERSION LESS 5)

IF(PHP5_EXECUTABLE AND PHP5_INCLUDES)
    SET(PHP5_FOUND "yes")
    MESSAGE(STATUS "Found PHP5-Version ${PHP5_VERSION} in ${PHP5_PREFIX}")
ENDIF(PHP5_EXECUTABLE AND PHP5_INCLUDES)
